<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111; }
        h1 { font-size: 20px; margin-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; }
        th { background: #f2f2f2; }
        .total { text-align: right; font-weight: bold; }
    </style>
</head>
<body>
    <h1>{{ $title ?? 'Document Title' }}</h1>
    <p>{{ $subtitle ?? 'Generated by Nexora Tools' }}</p>

    @if(!empty($items))
        <table>
            <thead>
                <tr><th>#</th><th>Item</th><th>Amount</th></tr>
            </thead>
            <tbody>
                @foreach($items as $i => $row)
                    <tr>
                        <td>{{ $i + 1 }}</td>
                        <td>{{ $row['label'] ?? '' }}</td>
                        <td>{{ $row['amount'] ?? '' }}</td>
                    </tr>
                @endforeach
            </tbody>
            @isset($total)
                <tfoot>
                    <tr><td colspan="2" class="total">Total</td><td>{{ $total }}</td></tr>
                </tfoot>
            @endisset
        </table>
    @endif
</body>
</html>
